spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: user-service
  main:
    allow-circular-references: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC

